# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on:
      group: default
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on:
      group: default
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
        with: # All of theses inputs are optional
          tag_name: "%s"
          tag_message: "%s"
          commit_pattern: "^Release (\\S+)"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLIC_TOKEN }} # You need to set this in your repo settings
